services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      # Maps your HA configuration to a local folder so data persists across reboots
      - ./ha_config:/config
      # Syncs the container time with your Pi's system time (crucial for automations)
      - /etc/localtime:/etc/localtime:ro
      # Exposes the Pi's Bluetooth hardware to Home Assistant
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  music-assistant:
    container_name: music-assistant
    image: "ghcr.io/music-assistant/server:latest"
    volumes:
      # Maps the Music Assistant database and settings
      - ./ma_data:/data
    restart: unless-stopped
    # Host network is required for discovering Wi-Fi speakers and mDNS broadcasting
    network_mode: host
  
  po-token-server:
    container_name: po-token-server
    image: brainicism/bgutil-ytdlp-pot-provider:latest
    restart: unless-stopped
    ports:
      - "4416:4416"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ~/docker/mosquitto/config:/mosquitto/config
      - ~/docker/mosquitto/data:/mosquitto/data
      - ~/docker/mosquitto/log:/mosquitto/log
    restart: unless-stopped
    # Since HA is using 'host' network mode, exposing Mosquitto's ports 
    # to the host allows HA to reach it via the host's IP address.